export const DIRECTORY_COPY = {
  es: {
    title: 'Encuentra servicios y profesionales con Wisdom',
    description: 'Explora servicios a domicilio, online y profesionales en Wisdom. Limpieza, reparaciones, clases, freelancers y más: qué comparar y cómo reservar.',
    intro: 'Wisdom es una app de servicios para conectar a personas que necesitan ayuda con profesionales que ofrecen su trabajo. Puedes buscar servicios presenciales y online, comparar ofertas y gestionar tus reservas desde una misma cuenta.',
    catalog: 'Qué servicio necesitas', pets: 'Mascotas', guides: 'Guías para elegir un servicio', read: 'Ver guía',
    localTitle: 'Servicios a domicilio y cerca de ti',
    local: 'Para buscar en España, introduce la ubicación donde necesitas el servicio. Revisa si el profesional se desplaza a tu domicilio o atiende en otro lugar. En limpieza, mantenimiento o cuidado de mascotas, concreta las tareas, la duración y el horario antes de reservar. Las categorías de esta página son una guía; las ofertas disponibles se consultan en la app.',
    onlineTitle: 'Servicios online y freelancers',
    online: 'Si el trabajo puede realizarse a distancia, busca una oferta online. Puedes explorar desarrollo web y de apps, diseño, edición de vídeo o clases. Define el resultado que necesitas, el idioma de comunicación, los plazos y los archivos o materiales que debes entregar. Compara servicios con un alcance equivalente, no solo su precio inicial.',
    compareTitle: 'Cómo comparar profesionales',
    compare: 'Lee la descripción completa, el perfil y las reseñas disponibles. Comprueba qué incluye la oferta, cómo se calcula el precio y qué condiciones se aplican. Una solicitud de reserva no equivale a una cita confirmada: revisa su estado y la aceptación del profesional en la app.',
    proTitle: 'Ofrece tus servicios profesionales',
    pro: 'Si trabajas por tu cuenta o quieres publicar un servicio, utiliza el modo profesional de Wisdom. Describe lo que haces, define precios y disponibilidad y gestiona las solicitudes de tus clientes. Puedes ofrecer trabajo presencial u online según las características de tu servicio.',
    availability: 'Wisdom es la plataforma intermediaria; cada profesional presta su servicio. La disponibilidad, los precios, los desplazamientos y los idiomas dependen de cada oferta. Esta página no es un listado de profesionales disponibles en tiempo real.',
    home: 'Inicio', language: 'Idioma', faq: 'Preguntas frecuentes', download: 'Descargar Wisdom', steps: 'Cómo funciona la app',
    stepItems: ['Busca una tarea y elige la ubicación o modalidad online.', 'Compara el alcance, el perfil, el precio y las reseñas disponibles.', 'Solicita la reserva y comprueba su confirmación en la app.'],
  },
  en: {
    title: 'Find services and professionals with Wisdom',
    description: 'Explore home services, online services and professionals on Wisdom. Cleaning, repairs, lessons and freelancers: what to compare and how to book.',
    intro: 'Wisdom is a services app connecting people who need help with professionals offering their skills. Search for in-person and online services, compare offers and manage bookings from the same account.',
    catalog: 'What service do you need?', pets: 'Pets', guides: 'Guides to choosing a service', read: 'Read guide',
    localTitle: 'Home services and local professionals',
    local: 'To search in Spain, enter the location where you need the service. Check whether the professional visits your home or works at another location. For cleaning, maintenance or pet care, agree on tasks, duration and timing before booking. The categories on this page are a guide; current offers are available in the app.',
    onlineTitle: 'Online services and freelancers',
    online: 'If the work can be done remotely, look for an online offer. Explore web and app development, design, video editing or lessons. Define the result you need, the working language, deadlines and any files or materials you must provide. Compare services with equivalent scope rather than only their starting prices.',
    compareTitle: 'How to compare professionals',
    compare: 'Read the full description, profile and available reviews. Check what is included, how the price is calculated and which conditions apply. A booking request is not a confirmed appointment: check its status and the professional’s acceptance in the app.',
    proTitle: 'Offer your professional services',
    pro: 'If you are self-employed or want to publish a service, use Wisdom’s professional mode. Describe your work, set prices and availability and manage customer requests. Offer in-person or online work according to the nature of your service.',
    availability: 'Wisdom is the intermediary platform; each professional delivers their own service. Availability, prices, travel areas and languages depend on each offer. This page is not a live listing of available professionals.',
    home: 'Home', language: 'Language', faq: 'Frequently asked questions', download: 'Download Wisdom', steps: 'How the app works',
    stepItems: ['Search for a task and choose a location or online format.', 'Compare scope, profile, price and available reviews.', 'Request a booking and check its confirmation in the app.'],
  },
  ca: {
    title: 'Troba serveis i professionals amb Wisdom', description: 'Explora serveis a domicili, online i professionals a Wisdom: neteja, reparacions, classes i freelancers. Descobreix què comparar abans de reservar.',
    intro: 'Wisdom és una app de serveis que connecta persones que necessiten ajuda amb professionals que ofereixen la seva feina. Busca serveis presencials i online, compara ofertes i gestiona les reserves des del mateix compte.',
    catalog: 'Quin servei necessites?', pets: 'Mascotes', guides: 'Guies per triar un servei', read: 'Veure guia',
    localTitle: 'Serveis a domicili i a prop teu', local: 'Per cercar a Espanya, indica la ubicació on necessites el servei. Comprova si el professional es desplaça al teu domicili o atén en un altre lloc. En neteja, manteniment o cura de mascotes, concreta les tasques, la durada i l’horari abans de reservar. Consulta les ofertes actuals a l’app.',
    onlineTitle: 'Serveis online i freelancers', online: 'Si la feina es pot fer a distància, busca una oferta online. Pots explorar desenvolupament web i d’apps, disseny, edició de vídeo o classes. Defineix el resultat, l’idioma de comunicació, els terminis i els materials que aportaràs. Compara serveis amb un abast equivalent.',
    compareTitle: 'Com comparar professionals', compare: 'Llegeix la descripció completa, el perfil i les valoracions disponibles. Revisa què inclou l’oferta, com es calcula el preu i les condicions. Una sol·licitud de reserva no és una cita confirmada: comprova’n l’estat i l’acceptació del professional a l’app.',
    proTitle: 'Ofereix els teus serveis professionals', pro: 'Fes servir el mode professional per publicar serveis, descriure la teva feina i definir preus i disponibilitat. Gestiona les sol·licituds dels clients i ofereix feina presencial o online segons el servei.',
    availability: 'Wisdom és la plataforma intermediària; cada professional presta el seu servei. La disponibilitat, els preus, els desplaçaments i els idiomes depenen de cada oferta. Aquesta pàgina no mostra disponibilitat en temps real.',
    home: 'Inici', language: 'Idioma', faq: 'Preguntes freqüents', download: 'Descarregar Wisdom', steps: 'Com funciona l’app', stepItems: ['Busca una tasca i tria ubicació o modalitat online.', 'Compara l’abast, el perfil, el preu i les valoracions.', 'Sol·licita la reserva i comprova’n la confirmació a l’app.'],
  },
  fr: {
    title: 'Trouvez des services et des professionnels avec Wisdom', description: 'Explorez les services à domicile et en ligne sur Wisdom : ménage, réparations, cours et freelances. Comparez les prestations avant de réserver.',
    intro: 'Wisdom est une application qui met en relation les personnes ayant besoin d’aide et les professionnels proposant leurs compétences. Recherchez des services en personne ou en ligne, comparez les offres et gérez vos réservations depuis un même compte.',
    catalog: 'De quel service avez-vous besoin ?', pets: 'Animaux', guides: 'Guides pour choisir un service', read: 'Lire le guide',
    localTitle: 'Services à domicile et professionnels à proximité', local: 'Pour une recherche en Espagne, indiquez le lieu où vous avez besoin du service. Vérifiez si le professionnel se déplace chez vous ou vous reçoit ailleurs. Pour le ménage, l’entretien ou la garde d’animaux, précisez les tâches, la durée et les horaires. Consultez les offres actuelles dans l’application.',
    onlineTitle: 'Services en ligne et freelances', online: 'Pour une prestation à distance, recherchez une offre en ligne : développement web ou mobile, design, montage vidéo ou cours. Définissez le résultat attendu, la langue de travail, les délais et les documents à fournir. Comparez des prestations de portée équivalente.',
    compareTitle: 'Comment comparer les professionnels', compare: 'Lisez la description, le profil et les avis disponibles. Vérifiez les prestations incluses, le calcul du prix et les conditions. Une demande de réservation ne confirme pas le rendez-vous : consultez son statut et l’acceptation du professionnel dans l’application.',
    proTitle: 'Proposez vos services professionnels', pro: 'Utilisez le mode professionnel pour publier vos services, présenter votre travail et définir vos tarifs et disponibilités. Gérez les demandes de vos clients pour des prestations en personne ou en ligne.',
    availability: 'Wisdom est une plateforme intermédiaire. Chaque professionnel réalise sa prestation. La disponibilité, les tarifs, les déplacements et les langues dépendent de chaque offre. Cette page ne présente pas les disponibilités en temps réel.',
    home: 'Accueil', language: 'Langue', faq: 'Questions fréquentes', download: 'Télécharger Wisdom', steps: 'Comment fonctionne l’application', stepItems: ['Recherchez une tâche et choisissez un lieu ou une prestation en ligne.', 'Comparez le contenu, le profil, le prix et les avis.', 'Demandez une réservation et vérifiez sa confirmation dans l’application.'],
  },
  pt: {
    title: 'Encontre serviços e profissionais com a Wisdom', description: 'Explore serviços ao domicílio e online na Wisdom: limpeza, reparações, aulas e freelancers. Saiba o que comparar antes de reservar.',
    intro: 'A Wisdom é uma app de serviços que liga quem precisa de ajuda a profissionais que oferecem o seu trabalho. Procure serviços presenciais e online, compare ofertas e gira reservas na mesma conta.',
    catalog: 'De que serviço precisa?', pets: 'Animais de estimação', guides: 'Guias para escolher um serviço', read: 'Ler guia',
    localTitle: 'Serviços ao domicílio e perto de si', local: 'Para pesquisar em Espanha, indique o local onde precisa do serviço. Confirme se o profissional se desloca a sua casa ou atende noutro local. Para limpeza, manutenção ou cuidados de animais, defina as tarefas, a duração e o horário antes de reservar. Consulte as ofertas atuais na app.',
    onlineTitle: 'Serviços online e freelancers', online: 'Se o trabalho pode ser feito à distância, procure uma oferta online: desenvolvimento web e de apps, design, edição de vídeo ou aulas. Defina o resultado pretendido, o idioma, os prazos e os materiais que deve fornecer. Compare serviços com um âmbito equivalente.',
    compareTitle: 'Como comparar profissionais', compare: 'Leia a descrição completa, o perfil e as avaliações disponíveis. Verifique o que está incluído, o cálculo do preço e as condições. Um pedido de reserva não é uma marcação confirmada: consulte o estado e a aceitação do profissional na app.',
    proTitle: 'Ofereça os seus serviços profissionais', pro: 'Use o modo profissional para publicar serviços, descrever o seu trabalho e definir preços e disponibilidade. Gira pedidos dos clientes para serviços presenciais ou online.',
    availability: 'A Wisdom é a plataforma intermediária; cada profissional presta o seu serviço. A disponibilidade, os preços, as deslocações e os idiomas dependem de cada oferta. Esta página não apresenta disponibilidade em tempo real.',
    home: 'Início', language: 'Idioma', faq: 'Perguntas frequentes', download: 'Descarregar Wisdom', steps: 'Como funciona a app', stepItems: ['Procure uma tarefa e escolha o local ou a modalidade online.', 'Compare o âmbito, o perfil, o preço e as avaliações.', 'Peça uma reserva e verifique a confirmação na app.'],
  },
  de: {
    title: 'Dienstleistungen und Fachleute mit Wisdom finden', description: 'Entdecke Dienstleistungen vor Ort und online: Reinigung, Reparaturen, Unterricht und Freelancer. Vergleiche Angebote und erfahre, wie du buchst.',
    intro: 'Wisdom verbindet Menschen, die Unterstützung suchen, mit Fachleuten, die ihre Leistungen anbieten. Suche nach Dienstleistungen vor Ort oder online, vergleiche Angebote und verwalte Buchungen mit einem Konto.',
    catalog: 'Welche Dienstleistung brauchst du?', pets: 'Haustiere', guides: 'Ratgeber zur Auswahl', read: 'Ratgeber lesen',
    localTitle: 'Dienstleistungen zu Hause und in deiner Nähe', local: 'Gib für eine Suche in Spanien den Ort an, an dem du Hilfe brauchst. Prüfe, ob die Fachkraft zu dir kommt oder an einem anderen Ort arbeitet. Kläre bei Reinigung, Instandhaltung oder Tierbetreuung Aufgaben, Dauer und Termin vor der Buchung. Aktuelle Angebote findest du in der App.',
    onlineTitle: 'Online-Dienstleistungen und Freelancer', online: 'Für Arbeiten aus der Ferne kannst du Online-Angebote suchen, etwa Web- und App-Entwicklung, Design, Videoschnitt oder Unterricht. Lege das gewünschte Ergebnis, die Arbeitssprache, Fristen und benötigte Unterlagen fest. Vergleiche Leistungen mit ähnlichem Umfang.',
    compareTitle: 'Fachleute vergleichen', compare: 'Lies die vollständige Beschreibung, das Profil und vorhandene Bewertungen. Prüfe Leistungsumfang, Preisberechnung und Bedingungen. Eine Buchungsanfrage ist noch kein bestätigter Termin: Prüfe den Status und die Annahme durch die Fachkraft in der App.',
    proTitle: 'Eigene Dienstleistungen anbieten', pro: 'Veröffentliche deine Leistungen im professionellen Modus von Wisdom. Beschreibe deine Arbeit, lege Preise und Verfügbarkeit fest und verwalte Kundenanfragen für Leistungen vor Ort oder online.',
    availability: 'Wisdom ist die Vermittlungsplattform. Die jeweilige Fachkraft erbringt die Leistung. Verfügbarkeit, Preise, Einsatzgebiete und Sprachen hängen vom Angebot ab. Diese Seite zeigt keine Verfügbarkeit in Echtzeit.',
    home: 'Startseite', language: 'Sprache', faq: 'Häufige Fragen', download: 'Wisdom herunterladen', steps: 'So funktioniert die App', stepItems: ['Suche nach einer Aufgabe und wähle einen Ort oder Online-Service.', 'Vergleiche Umfang, Profil, Preis und Bewertungen.', 'Frage eine Buchung an und prüfe die Bestätigung in der App.'],
  },
  it: {
    title: 'Trova servizi e professionisti con Wisdom', description: 'Esplora servizi a domicilio e online su Wisdom: pulizie, riparazioni, lezioni e freelance. Scopri cosa confrontare prima di prenotare.',
    intro: 'Wisdom è un’app che mette in contatto chi cerca aiuto con professionisti che offrono il proprio lavoro. Cerca servizi in presenza e online, confronta le offerte e gestisci le prenotazioni con un unico account.',
    catalog: 'Di quale servizio hai bisogno?', pets: 'Animali domestici', guides: 'Guide per scegliere un servizio', read: 'Leggi la guida',
    localTitle: 'Servizi a domicilio e vicino a te', local: 'Per cercare in Spagna, indica il luogo in cui ti serve il servizio. Verifica se il professionista viene a casa tua o riceve altrove. Per pulizie, manutenzione o cura degli animali, chiarisci attività, durata e orari prima di prenotare. Consulta le offerte attuali nell’app.',
    onlineTitle: 'Servizi online e freelance', online: 'Per lavori a distanza, cerca un’offerta online: sviluppo web e di app, design, montaggio video o lezioni. Definisci il risultato, la lingua di lavoro, le scadenze e i materiali da fornire. Confronta prestazioni con un ambito equivalente.',
    compareTitle: 'Come confrontare i professionisti', compare: 'Leggi la descrizione completa, il profilo e le recensioni disponibili. Verifica cosa è incluso, il calcolo del prezzo e le condizioni. Una richiesta di prenotazione non conferma l’appuntamento: controlla lo stato e l’accettazione del professionista nell’app.',
    proTitle: 'Offri i tuoi servizi professionali', pro: 'Usa la modalità professionale per pubblicare servizi, descrivere il tuo lavoro e impostare prezzi e disponibilità. Gestisci le richieste dei clienti per prestazioni in presenza o online.',
    availability: 'Wisdom è la piattaforma intermediaria; ogni professionista eroga il proprio servizio. Disponibilità, prezzi, spostamenti e lingue dipendono dall’offerta. Questa pagina non mostra disponibilità in tempo reale.',
    home: 'Home', language: 'Lingua', faq: 'Domande frequenti', download: 'Scarica Wisdom', steps: 'Come funziona l’app', stepItems: ['Cerca un’attività e scegli il luogo o la modalità online.', 'Confronta ambito, profilo, prezzo e recensioni.', 'Richiedi una prenotazione e controlla la conferma nell’app.'],
  },
  zh: {
    title: '通过 Wisdom 寻找服务和专业人士', description: '探索 Wisdom 的上门服务和在线服务：清洁、维修、私人课程及自由职业服务。了解如何比较服务内容并预约。',
    intro: 'Wisdom 是一款连接服务需求者与专业人士的应用。你可以搜索线下和在线服务、比较不同报价，并通过同一个账户管理预约。',
    catalog: '你需要什么服务？', pets: '宠物', guides: '服务选择指南', read: '阅读指南',
    localTitle: '上门服务和附近的专业人士', local: '在西班牙搜索时，请输入需要服务的地点。确认专业人士是否提供上门服务，还是需要你前往指定地点。预约清洁、维护或宠物照护时，应先明确任务、时长和时间安排。此处的分类用于了解服务，当前可用的报价请在应用内查询。',
    onlineTitle: '在线服务和自由职业者', online: '如果工作可以远程完成，请查找在线服务，例如网站与应用开发、设计、视频剪辑或课程。说明期望成果、沟通语言、截止日期，以及需要提供的文件或材料。比较服务时，应考虑相同的工作范围，而不只是起始价格。',
    compareTitle: '如何比较专业人士', compare: '阅读完整的服务说明、个人资料和已有评价。确认包含哪些工作、价格如何计算以及适用条件。提交预约申请并不代表预约已确认，请在应用内查看状态和专业人士是否接受。',
    proTitle: '发布你的专业服务', pro: '使用 Wisdom 的专业模式发布服务、介绍你的工作，并设置价格和可预约时间。根据服务特点提供线下或在线服务，管理客户的预约申请。',
    availability: 'Wisdom 是中介平台，服务由各专业人士提供。可用性、价格、出行范围和语言取决于具体报价。本页面不显示专业人士的实时可用情况。',
    home: '首页', language: '语言', faq: '常见问题', download: '下载 Wisdom', steps: '应用使用方式', stepItems: ['搜索任务并选择服务地点或在线方式。', '比较工作范围、资料、价格和已有评价。', '提交预约申请，并在应用内查看确认状态。'],
  },
  ar: {
    title: 'اعثر على خدمات ومحترفين مع Wisdom', description: 'استكشف خدمات منزلية وعبر الإنترنت في Wisdom: التنظيف والإصلاح والدروس والعمل المستقل. تعرّف على ما يجب مقارنته قبل الحجز.',
    intro: 'Wisdom تطبيق خدمات يربط الأشخاص الذين يحتاجون إلى مساعدة بالمحترفين الذين يعرضون مهاراتهم. ابحث عن خدمات حضورية أو عبر الإنترنت وقارن العروض وأدر حجوزاتك من حساب واحد.',
    catalog: 'ما الخدمة التي تحتاجها؟', pets: 'الحيوانات الأليفة', guides: 'أدلة اختيار الخدمة', read: 'اقرأ الدليل',
    localTitle: 'خدمات منزلية ومحترفون بالقرب منك', local: 'للبحث في إسبانيا، أدخل الموقع الذي تحتاج فيه إلى الخدمة. تحقق مما إذا كان المحترف يأتي إلى منزلك أو يستقبلك في مكان آخر. حدّد المهام والمدة والموعد قبل حجز التنظيف أو الصيانة أو رعاية الحيوانات. تعرض هذه الصفحة فئات الخدمات، ويمكنك الاطلاع على العروض الحالية في التطبيق.',
    onlineTitle: 'خدمات عبر الإنترنت ومستقلون', online: 'إذا أمكن تنفيذ العمل عن بُعد، ابحث عن عرض عبر الإنترنت، مثل تطوير المواقع والتطبيقات أو التصميم أو تحرير الفيديو أو الدروس. حدّد النتيجة المطلوبة ولغة التواصل والمواعيد والملفات التي ستقدمها. قارن الخدمات ذات النطاق المتكافئ، وليس سعر البداية وحده.',
    compareTitle: 'كيف تقارن بين المحترفين؟', compare: 'اقرأ الوصف الكامل والملف والتقييمات المتاحة. تحقق من المهام المشمولة وطريقة حساب السعر والشروط. طلب الحجز لا يعني تأكيد الموعد؛ راجع حالة الطلب وقبول المحترف في التطبيق.',
    proTitle: 'اعرض خدماتك المهنية', pro: 'استخدم الوضع المهني في Wisdom لنشر خدماتك ووصف عملك وتحديد الأسعار والتوافر. أدر طلبات العملاء وقدّم خدمات حضورية أو عبر الإنترنت وفق طبيعة عملك.',
    availability: 'Wisdom منصة وسيطة، ويقدّم كل محترف خدمته. يعتمد التوافر والأسعار ومناطق التنقل واللغات على كل عرض. لا تعرض هذه الصفحة التوافر في الوقت الفعلي.',
    home: 'الرئيسية', language: 'اللغة', faq: 'الأسئلة الشائعة', download: 'تنزيل Wisdom', steps: 'كيف يعمل التطبيق؟', stepItems: ['ابحث عن مهمة وحدّد الموقع أو الخدمة عبر الإنترنت.', 'قارن نطاق العمل والملف والسعر والتقييمات.', 'أرسل طلب حجز وتحقق من تأكيده في التطبيق.'],
  },
  hi: {
    title: 'Wisdom के साथ सेवाएँ और पेशेवर खोजें', description: 'Wisdom पर घरेलू और ऑनलाइन सेवाएँ खोजें: सफ़ाई, मरम्मत, कक्षाएँ और फ्रीलांसर। बुकिंग से पहले सही तुलना करना सीखें।',
    intro: 'Wisdom एक सेवा ऐप है जो मदद चाहने वालों को अपना काम पेश करने वाले पेशेवरों से जोड़ता है। एक ही खाते से प्रत्यक्ष और ऑनलाइन सेवाएँ खोजें, ऑफ़र की तुलना करें और बुकिंग संभालें।',
    catalog: 'आपको कौन सी सेवा चाहिए?', pets: 'पालतू जानवर', guides: 'सेवा चुनने की मार्गदर्शिकाएँ', read: 'मार्गदर्शिका पढ़ें',
    localTitle: 'घरेलू सेवाएँ और नज़दीकी पेशेवर', local: 'स्पेन में खोजने के लिए वह स्थान दर्ज करें जहाँ सेवा चाहिए। जाँचें कि पेशेवर आपके घर आएगा या आपको किसी अन्य स्थान पर जाना होगा। सफ़ाई, रखरखाव या पालतू जानवरों की देखभाल बुक करने से पहले काम, अवधि और समय स्पष्ट करें। मौजूदा ऑफ़र ऐप में देखें।',
    onlineTitle: 'ऑनलाइन सेवाएँ और फ्रीलांसर', online: 'अगर काम दूर से हो सकता है, तो वेबसाइट और ऐप विकास, डिज़ाइन, वीडियो संपादन या कक्षाओं जैसे ऑनलाइन ऑफ़र खोजें। अपेक्षित परिणाम, बातचीत की भाषा, समय सीमा और दी जाने वाली फ़ाइलें तय करें। केवल शुरुआती कीमत नहीं, बल्कि समान कार्यक्षेत्र वाली सेवाओं की तुलना करें।',
    compareTitle: 'पेशेवरों की तुलना कैसे करें', compare: 'पूरा विवरण, प्रोफ़ाइल और उपलब्ध समीक्षाएँ पढ़ें। देखें कि क्या शामिल है, कीमत कैसे तय होती है और कौन सी शर्तें लागू हैं। बुकिंग अनुरोध भेजना पुष्टि नहीं है; ऐप में स्थिति और पेशेवर की स्वीकृति जाँचें।',
    proTitle: 'अपनी पेशेवर सेवाएँ पेश करें', pro: 'Wisdom के पेशेवर मोड से सेवाएँ प्रकाशित करें, अपना काम बताएँ और कीमत व उपलब्धता तय करें। काम के अनुसार प्रत्यक्ष या ऑनलाइन सेवाएँ दें और ग्राहकों के अनुरोध संभालें।',
    availability: 'Wisdom मध्यस्थ प्लेटफ़ॉर्म है; प्रत्येक पेशेवर अपनी सेवा देता है। उपलब्धता, कीमत, यात्रा क्षेत्र और भाषाएँ हर ऑफ़र पर निर्भर हैं। यह पेज वास्तविक समय की उपलब्धता नहीं दिखाता।',
    home: 'होम', language: 'भाषा', faq: 'अक्सर पूछे जाने वाले सवाल', download: 'Wisdom डाउनलोड करें', steps: 'ऐप कैसे काम करता है', stepItems: ['काम खोजें और स्थान या ऑनलाइन विकल्प चुनें।', 'कार्यक्षेत्र, प्रोफ़ाइल, कीमत और समीक्षाओं की तुलना करें।', 'बुकिंग का अनुरोध करें और ऐप में पुष्टि जाँचें।'],
  },
  ja: {
    title: 'Wisdomでサービスと専門家を探す', description: 'Wisdomの訪問・オンラインサービスを探しましょう。清掃、修理、個人レッスン、フリーランスへの依頼を比較し、予約方法を確認できます。',
    intro: 'Wisdomは、サポートを必要とする人とスキルを提供する専門家をつなぐサービスアプリです。対面・オンラインのサービスを検索し、内容を比較して、一つのアカウントで予約を管理できます。',
    catalog: 'どんなサービスが必要ですか？', pets: 'ペット', guides: 'サービス選びのガイド', read: 'ガイドを読む',
    localTitle: '訪問サービスと近くの専門家', local: 'スペインで検索する場合は、サービスが必要な場所を入力してください。専門家が自宅を訪問するのか、指定の場所へ行く必要があるのかを確認しましょう。清掃、メンテナンス、ペットケアでは、作業内容、所要時間、日時を予約前に確認します。現在の募集内容はアプリで確認できます。',
    onlineTitle: 'オンラインサービスとフリーランス', online: '遠隔でできる仕事なら、ウェブ・アプリ開発、デザイン、動画編集、レッスンなどのオンラインサービスを探せます。必要な成果物、使用言語、期限、提供する資料を明確にしましょう。最初に表示される料金だけでなく、同じ作業範囲で比較することが大切です。',
    compareTitle: '専門家を比較するには', compare: 'サービスの説明全文、プロフィール、掲載されているレビューを読みましょう。含まれる作業、料金の計算方法、条件を確認してください。予約リクエストは予約確定ではありません。アプリで状態と専門家の承認を確認します。',
    proTitle: '自分のサービスを掲載する', pro: 'Wisdomのプロフェッショナルモードで仕事内容を紹介し、料金や対応可能な時間を設定できます。サービスの内容に合わせて対面またはオンラインで提供し、顧客からの依頼を管理しましょう。',
    availability: 'Wisdomは仲介プラットフォームで、各専門家がサービスを提供します。空き状況、料金、訪問範囲、対応言語は各サービスによって異なります。このページはリアルタイムの空き状況を示すものではありません。',
    home: 'ホーム', language: '言語', faq: 'よくある質問', download: 'Wisdomをダウンロード', steps: 'アプリの使い方', stepItems: ['作業を検索し、場所またはオンライン形式を選びます。', '作業範囲、プロフィール、料金、レビューを比較します。', '予約をリクエストし、アプリで確定を確認します。'],
  },
  ru: {
    title: 'Находите услуги и специалистов с Wisdom', description: 'Услуги на дому и онлайн в Wisdom: уборка, ремонт, частные уроки и фриланс. Узнайте, как сравнить предложения и оформить бронирование.',
    intro: 'Wisdom — приложение, которое связывает людей, нуждающихся в помощи, со специалистами, предлагающими свои услуги. Ищите очные и онлайн-услуги, сравнивайте предложения и управляйте бронированиями в одном аккаунте.',
    catalog: 'Какая услуга вам нужна?', pets: 'Домашние животные', guides: 'Руководства по выбору услуг', read: 'Читать руководство',
    localTitle: 'Услуги на дому и специалисты рядом', local: 'Для поиска в Испании укажите место, где нужна услуга. Проверьте, выезжает ли специалист к вам или принимает в другом месте. Перед заказом уборки, обслуживания дома или ухода за животными уточните задачи, длительность и время. Актуальные предложения доступны в приложении.',
    onlineTitle: 'Онлайн-услуги и фрилансеры', online: 'Для удалённой работы ищите онлайн-предложения: разработку сайтов и приложений, дизайн, видеомонтаж или уроки. Определите нужный результат, язык общения, сроки и материалы, которые вы предоставите. Сравнивайте услуги с одинаковым объёмом работ, а не только начальные цены.',
    compareTitle: 'Как сравнить специалистов', compare: 'Читайте полное описание, профиль и доступные отзывы. Уточняйте состав услуги, расчёт цены и условия. Запрос на бронирование ещё не подтверждает встречу: проверьте статус и согласие специалиста в приложении.',
    proTitle: 'Предлагайте профессиональные услуги', pro: 'В профессиональном режиме Wisdom можно публиковать услуги, описывать работу, устанавливать цены и доступное время. Управляйте запросами клиентов и предлагайте очную или удалённую работу в зависимости от услуги.',
    availability: 'Wisdom — платформа-посредник; каждый специалист оказывает свою услугу. Доступность, цены, зоны выезда и языки зависят от предложения. Эта страница не показывает доступность в реальном времени.',
    home: 'Главная', language: 'Язык', faq: 'Частые вопросы', download: 'Скачать Wisdom', steps: 'Как работает приложение', stepItems: ['Найдите задачу и выберите место или онлайн-формат.', 'Сравните объём работ, профиль, цену и отзывы.', 'Отправьте запрос и проверьте подтверждение в приложении.'],
  },
};
