// Guías editoriales originales. Sin tarifas, reseñas ni cobertura local inventadas.
export const SERVICE_GUIDES = {
  home: {
    ids: [1, 2, 3, 5, 6, 8, 317, 318],
    es: {
      title: 'Servicios a domicilio: cómo encontrar al profesional adecuado',
      description: 'Busca servicios a domicilio con Wisdom. Aprende a comparar limpieza, reparaciones y cuidado de mascotas según ubicación, tareas, duración y condiciones.',
      intro: 'Un servicio a domicilio debe encajar con la tarea y con las condiciones de tu vivienda. Wisdom permite buscar profesionales y comparar ofertas, pero el desplazamiento y el trabajo incluido los define cada profesional. Esta guía te ayuda a preparar la búsqueda y revisar una oferta antes de enviar una reserva.',
      sections: [
        ['Empieza por la tarea y la ubicación', 'Especifica qué necesitas resolver y dónde se realizará el trabajo. Buscar limpieza de cocina, pintar una habitación o pasear un perro da más contexto que pedir ayuda para casa. En España, introduce en la app la ubicación concreta; la existencia de una categoría no significa que haya profesionales disponibles en todos los municipios.'],
        ['Comprueba qué tipo de servicio estás reservando', 'Distingue entre una visita a tu domicilio, una cita en el lugar del profesional y un servicio online. Revisa el alcance, la duración, los materiales y los posibles desplazamientos. Si necesitas varias tareas, confirma que pertenecen a la misma oferta en lugar de asumir que todas están incluidas.'],
        ['Compara propuestas equivalentes', 'Valora conjuntamente la descripción, el perfil, las reseñas y el importe que se muestra al reservar. Una tarifa por hora y un precio por trabajo pueden cubrir cosas distintas. La duración, el estado de la vivienda y el equipo necesario ayudan a entender qué estás comparando.'],
        ['Prepara la visita', 'Facilita las indicaciones necesarias para acceder, despeja las zonas donde se trabajará y comunica cualquier condición relevante para la tarea. Revisa la confirmación, la fecha y la política de cancelación en la reserva. No des por confirmada una visita por haber enviado la solicitud.'],
      ],
      checklist: ['Tarea concreta y zonas de trabajo.', 'Ubicación, acceso y modalidad presencial.', 'Duración, fecha y horario solicitados.', 'Materiales incluidos y condiciones de la oferta.'],
      question: '¿Puedo reservar servicios a domicilio recurrentes?', answer: 'Wisdom permite reservas recurrentes en las ofertas que las admiten. Comprueba la frecuencia, las sesiones y las condiciones de esa oferta antes de configurar la recurrencia.',
    },
    en: {
      title: 'Home services: how to choose the right professional',
      description: 'Find home services with Wisdom. Compare cleaning, repairs and pet care by location, tasks, duration and booking conditions.',
      intro: 'A home service should match both your task and the conditions at your property. Wisdom lets you search for professionals and compare offers, while each professional defines their travel area and included work. Use this guide to prepare your search and review an offer before requesting a booking.',
      sections: [
        ['Start with the task and location', 'Describe what you need and where the work will happen. Kitchen cleaning, painting a room or walking a dog is more specific than asking for help at home. When searching in Spain, enter the actual location in the app; a listed category does not mean professionals are available in every town.'],
        ['Check the service format', 'Distinguish between a home visit, an appointment at the professional’s location and an online service. Review the scope, duration, materials and travel arrangements. If you need several tasks, check that the offer includes them rather than assuming they all belong to the same service.'],
        ['Compare equivalent proposals', 'Consider the description, profile, reviews and amount shown when booking together. An hourly rate and a fixed job price can cover different things. Duration, the condition of the property and required equipment help explain what you are comparing.'],
        ['Prepare for the visit', 'Provide the necessary access instructions, clear the work area and communicate relevant conditions. Check confirmation, date and cancellation terms in the booking. Sending a request alone does not confirm a visit.'],
      ],
      checklist: ['Specific task and work areas.', 'Location, access and in-person format.', 'Requested duration, date and time.', 'Included materials and offer conditions.'],
      question: 'Can I book recurring home services?', answer: 'Wisdom supports recurring bookings for offers that allow them. Review the frequency, sessions and offer conditions before setting up a recurring booking.',
    },
  },
  cleaning: {
    ids: [1],
    es: {
      title: 'Limpieza a domicilio: tareas, precios y reservas',
      description: 'Encuentra limpieza a domicilio en Wisdom. Revisa qué incluye el servicio, limpieza por horas, productos y reservas recurrentes antes de elegir profesional.',
      intro: 'Para encontrar limpieza del hogar, empieza por las zonas y tareas que necesitas atender. Una limpieza de mantenimiento y una limpieza de una vivienda con tareas acumuladas requieren alcances distintos. En Wisdom puedes consultar ofertas de limpieza y comparar sus condiciones antes de solicitar una reserva.',
      sections: [
        ['Define las tareas de limpieza', 'Anota habitaciones, baños, cocina y las superficies prioritarias. Si necesitas ventanas, interior de armarios, electrodomésticos o zonas de difícil acceso, comprueba que la descripción las incluya. No todas las ofertas cubren trabajos especiales ni todos los materiales pueden limpiarse del mismo modo.'],
        ['Limpieza por horas o por servicio', 'Consulta cómo se ha definido el precio: por tiempo o por un trabajo concreto. Para comparar, revisa también duración, tareas y tamaño del espacio. No hay una tarifa única de Wisdom para todos los profesionales; el importe aplicable y su desglose se muestran en la oferta y durante la reserva.'],
        ['Productos, equipo y preparación', 'Revisa quién aporta los productos y herramientas. Indica si hay superficies delicadas, mascotas o condiciones que afecten al trabajo. Retirar objetos de las zonas que se limpiarán puede facilitar la tarea, pero confirma con el profesional las instrucciones específicas de su servicio.'],
        ['Una limpieza puntual o periódica', 'Para una intervención puntual, concreta las prioridades. Si buscas mantenimiento periódico, revisa si la oferta admite reservas recurrentes y qué frecuencia y horarios puedes configurar. Cada solicitud y su estado se gestionan en la app; no presupongas disponibilidad futura por haber reservado una sesión.'],
      ],
      checklist: ['Zonas a limpiar y prioridades.', 'Tareas especiales expresamente incluidas.', 'Duración y forma de calcular el precio.', 'Productos, herramientas, acceso y horario.'],
      question: '¿Cómo encuentro limpieza cerca de mí?', answer: 'Busca limpieza del hogar en Wisdom e indica la ubicación donde necesitas el servicio. Consulta las ofertas que aparezcan y comprueba su zona de desplazamiento y disponibilidad.',
    },
    en: {
      title: 'Home cleaning: tasks, prices and bookings',
      description: 'Find home cleaning on Wisdom. Review included tasks, hourly cleaning, supplies and recurring bookings before choosing a professional.',
      intro: 'Start your home cleaning search with the areas and tasks that need attention. Regular maintenance and a property with accumulated cleaning tasks call for different scopes. On Wisdom, you can browse cleaning offers and compare their conditions before requesting a booking.',
      sections: [
        ['Define the cleaning tasks', 'List rooms, bathrooms, kitchen areas and priority surfaces. If you need windows, cupboard interiors, appliances or difficult-to-reach areas cleaned, check that the description includes them. Not every offer covers specialist tasks, and different materials require different treatment.'],
        ['Hourly cleaning or a fixed service', 'Check whether the price is based on time or a defined job. Compare duration, included tasks and space as well as price. Wisdom does not set one rate for every professional; the applicable amount and breakdown appear in the offer and booking process.'],
        ['Supplies, equipment and preparation', 'Check who provides products and tools. Mention delicate surfaces, pets or conditions that affect the job. Clearing objects from the cleaning area may help, but confirm any service-specific preparation with the professional.'],
        ['One-off or regular cleaning', 'For a one-off booking, specify your priorities. For regular maintenance, check whether the offer allows recurring bookings and which schedules can be configured. Manage each request and its status in the app; one booking does not guarantee future availability.'],
      ],
      checklist: ['Cleaning areas and priorities.', 'Any specialist tasks explicitly included.', 'Duration and pricing method.', 'Supplies, equipment, access and timing.'],
      question: 'How do I find a cleaner near me?', answer: 'Search for home cleaning in Wisdom and enter the location where you need the service. Review the offers shown, their travel areas and availability.',
    },
  },
  trades: {
    ids: [2, 3, 5, 6, 8, 151],
    es: {
      title: 'Profesionales de reparaciones y mantenimiento del hogar', description: 'Busca fontanería, electricidad, pintura, jardinería y reformas en Wisdom. Prepara la descripción del trabajo y compara el alcance de cada oferta.',
      intro: 'Una descripción concreta del trabajo facilita encontrar al profesional adecuado para una reparación o tarea de mantenimiento. Wisdom reúne categorías como fontanería, electricidad, albañilería, pintura, jardinería y arquitectura. Revisa las ofertas actuales en la app y las condiciones publicadas por cada profesional.',
      sections: [
        ['Describe el problema y el resultado esperado', 'Indica qué elemento necesita atención, qué ocurre y desde cuándo. Para pintura o jardinería, describe las superficies o zonas y el acabado esperado. Aporta las medidas o fotografías pertinentes cuando el flujo lo permita, evitando incluir datos personales que no sean necesarios para valorar el trabajo.'],
        ['Diferencia revisión, reparación y obra', 'Una visita de diagnóstico no equivale necesariamente a una reparación completa. Comprueba si el precio incluye mano de obra, materiales, retirada de residuos o desplazamiento. En un trabajo con varias fases, aclara qué parte cubre la oferta que vas a reservar.'],
        ['Revisa experiencia y requisitos del trabajo', 'Consulta el perfil, la descripción y las reseñas disponibles. Para trabajos que requieran habilitación o conocimientos específicos, comprueba que el profesional sea adecuado para esa intervención. La presencia de un perfil en la plataforma no sustituye la revisión de los requisitos concretos de tu proyecto.'],
        ['Coordina acceso y materiales', 'Antes de la visita, confirma cuándo puede acceder el profesional y quién aporta los materiales. Describe las limitaciones relevantes del espacio y verifica el estado de la reserva. No asumas que una búsqueda implica un servicio de urgencias o disponibilidad inmediata.'],
      ],
      checklist: ['Problema, medidas y resultado deseado.', 'Diagnóstico o reparación incluida.', 'Mano de obra, materiales y desplazamiento.', 'Acceso, horario y requisitos del trabajo.'],
      question: '¿Puedo buscar un fontanero o electricista por mi zona?', answer: 'Sí. Busca el oficio o la tarea e indica la ubicación en Wisdom. La app muestra las ofertas que correspondan a la búsqueda; comprueba en cada una el alcance y la disponibilidad.',
    },
    en: {
      title: 'Home repairs and maintenance professionals', description: 'Find plumbing, electrical work, painting, gardening and renovation services on Wisdom. Prepare your brief and compare what each offer includes.',
      intro: 'A clear description helps you find the right professional for repairs and maintenance. Wisdom includes categories such as plumbing, electrical work, masonry, painting, gardening and architecture. Check current offers in the app and each professional’s published conditions.',
      sections: [
        ['Describe the issue and expected result', 'Explain what needs attention, what is happening and when it started. For painting or gardening, describe the surfaces or areas and desired finish. Provide relevant dimensions or photos when the flow allows it, without unnecessary personal information.'],
        ['Separate inspection, repair and renovation', 'A diagnostic visit does not necessarily include a full repair. Check whether the price covers labour, materials, waste removal or travel. For work with multiple stages, clarify which stage is covered by the offer you intend to book.'],
        ['Review experience and job requirements', 'Check the profile, description and available reviews. For work requiring particular qualifications or knowledge, check that the professional is suitable for the task. Having a profile on the platform does not replace checking the requirements of your project.'],
        ['Coordinate access and materials', 'Confirm when the professional can access the property and who supplies materials. Explain relevant space limitations and check booking status. A search does not imply emergency assistance or immediate availability.'],
      ],
      checklist: ['Issue, dimensions and desired result.', 'Included inspection or repair.', 'Labour, materials and travel.', 'Access, timing and job requirements.'],
      question: 'Can I search for a plumber or electrician in my area?', answer: 'Yes. Search for the trade or task and enter your location in Wisdom. Review the matching offers in the app and check the scope and availability of each one.',
    },
  },
  lessons: {
    ids: [56, 57, 58, 59, 61, 65, 68],
    es: {
      title: 'Clases particulares presenciales y online', description: 'Explora clases de idiomas, matemáticas, ciencias, música y programación en Wisdom. Compara nivel, modalidad y duración antes de reservar.',
      intro: 'Elegir clases particulares empieza por definir qué quieres aprender y desde qué nivel partes. En Wisdom puedes explorar profesores particulares, idiomas, matemáticas, ciencias, música, programación y preparación de entrevistas. La modalidad y el contenido dependen de cada oferta.',
      sections: [
        ['Aclara tu objetivo y nivel', 'Distingue entre apoyo con una materia, preparación de una prueba, práctica de conversación o aprendizaje de una habilidad. Indica los conocimientos previos y el material que utilizas. Un objetivo concreto ayuda a comparar el enfoque de distintos profesores.'],
        ['Clases a domicilio, en otro lugar u online', 'Revisa dónde se imparte la clase y qué necesitas preparar. En una sesión online, confirma idioma, horario y recursos necesarios. Para una clase presencial, comprueba ubicación y desplazamientos; no todas las ofertas incluyen enseñanza a domicilio.'],
        ['Compara duración, contenidos y metodología', 'Comprueba cuánto dura cada sesión y si el precio corresponde a una clase o a otro formato. Lee qué materias y niveles cubre el profesor. Las reseñas y el perfil aportan contexto, pero deben valorarse junto con el contenido de la oferta.'],
        ['Organiza la continuidad', 'Si necesitas varias sesiones, revisa la disponibilidad y si la oferta admite recurrencia. Antes de cada clase, prepara los ejercicios o materiales acordados. Los resultados dependen del proceso de aprendizaje; una reserva no garantiza una nota, certificación o empleo.'],
      ],
      checklist: ['Materia, objetivo y nivel inicial.', 'Idioma y modalidad de la clase.', 'Duración, materiales y preparación.', 'Horario y condiciones de continuidad.'],
      question: '¿Puedo buscar clases en un idioma concreto?', answer: 'Revisa el idioma indicado en la oferta y descríbelo como requisito de tu búsqueda. En servicios online, comprueba que puedas comunicarte y seguir la clase en el idioma que necesitas.',
    },
    en: {
      title: 'Private lessons in person and online', description: 'Explore language, maths, science, music and programming lessons on Wisdom. Compare levels, formats and session duration before booking.',
      intro: 'Choosing private lessons starts with what you want to learn and your current level. On Wisdom, explore tutoring, languages, maths, science, music, programming and interview preparation. Format and lesson content depend on the individual offer.',
      sections: [
        ['Clarify your goal and starting level', 'Distinguish between subject support, exam preparation, conversation practice and learning a skill. Explain your previous knowledge and the materials you use. A specific goal helps you compare different teaching approaches.'],
        ['At home, at another venue or online', 'Check where the lesson takes place and what to prepare. For online sessions, confirm the language, time and necessary resources. For in-person lessons, review location and travel arrangements; not every offer includes home visits.'],
        ['Compare duration, content and approach', 'Check session length and whether the price covers one lesson or another format. Read which subjects and levels the tutor teaches. Reviews and profile information provide context alongside the actual lesson description.'],
        ['Plan continued learning', 'For several sessions, review availability and whether recurring bookings are supported. Prepare agreed exercises or materials before each lesson. Results depend on the learning process; a booking does not guarantee a grade, qualification or job.'],
      ],
      checklist: ['Subject, goal and starting level.', 'Language and lesson format.', 'Duration, materials and preparation.', 'Schedule and arrangements for future sessions.'],
      question: 'Can I find lessons in a particular language?', answer: 'Review the language stated in the offer and make it part of your search requirements. For online services, check that you can communicate and follow the lesson in the language you need.',
    },
  },
  online: {
    ids: [83, 84, 85, 86, 89, 90, 94, 100, 101],
    es: {
      title: 'Servicios online y freelancers para tu proyecto', description: 'Encuentra servicios digitales en Wisdom: desarrollo web y de apps, diseño, vídeo y contenido. Prepara un encargo claro antes de contratar a un freelancer.',
      intro: 'Un servicio online permite trabajar con un profesional a distancia cuando la tarea lo admite. En Wisdom puedes explorar desarrollo web, aplicaciones, frontend, backend, inteligencia artificial, diseño, edición de vídeo, diseño 3D y creación de contenido. Elige por especialidad y alcance del trabajo, además de por precio.',
      sections: [
        ['Prepara un encargo que se pueda valorar', 'Explica el objetivo, el público y el resultado que necesitas. Para una web, concreta páginas y funcionalidades; para diseño o vídeo, describe piezas, formatos y materiales de partida. Señala lo imprescindible y lo opcional para evitar comparar propuestas con alcances distintos.'],
        ['Comprueba entregables y revisiones', 'Lee qué archivos o resultados se incluyen, los plazos y si la oferta contempla revisiones. Aclara los formatos de entrega y las condiciones de uso del trabajo cuando sean relevantes. No presupongas mantenimiento continuo, archivos editables o cambios ilimitados si no aparecen en la descripción.'],
        ['Coordina idioma y horarios', 'La distancia no elimina la necesidad de coordinarse. Comprueba el idioma de comunicación y acuerda momentos para resolver dudas o revisar avances. Si una tarea depende de información o materiales tuyos, prepara esos recursos antes de la fecha acordada.'],
        ['Compara especialización y condiciones', 'Revisa el perfil, los ejemplos que el profesional haya publicado y las reseñas disponibles. Contrasta las tecnologías o herramientas que requiere tu proyecto con lo que ofrece. Comprueba el desglose de la reserva y las condiciones aplicables antes de solicitarla.'],
      ],
      checklist: ['Objetivo y lista de entregables.', 'Materiales de partida y formatos finales.', 'Plazos, revisiones e idioma de trabajo.', 'Qué incluye el precio y qué queda fuera.'],
      question: '¿Wisdom solo sirve para servicios a domicilio?', answer: 'No. Wisdom admite servicios presenciales y online. Para trabajo digital o remoto, comprueba que la oferta elegida indique la modalidad online y cubra el encargo que necesitas.',
    },
    en: {
      title: 'Online services and freelancers for your project', description: 'Find digital services on Wisdom: web and app development, design, video and content. Prepare a clear brief before hiring a freelancer.',
      intro: 'An online service lets you work remotely with a professional when the task allows it. Explore web and app development, frontend, backend, AI development, design, video editing, 3D design and content creation on Wisdom. Compare specialisation and scope alongside the price.',
      sections: [
        ['Prepare a brief that can be assessed', 'Explain the objective, audience and result you need. For a website, specify pages and features; for design or video, list assets, formats and source materials. Separate essential requirements from optional ones to avoid comparing different scopes.'],
        ['Check deliverables and revisions', 'Read which files or results are included, the timeline and whether revisions are covered. Clarify delivery formats and usage conditions when relevant. Do not assume ongoing maintenance, editable source files or unlimited changes unless the description includes them.'],
        ['Coordinate language and schedules', 'Remote work still needs coordination. Check the working language and agree on suitable times for questions or progress reviews. If the work depends on information or materials from you, prepare those resources before the agreed date.'],
        ['Compare specialisation and conditions', 'Review the profile, any examples published by the professional and available reviews. Match the technology or tools your project requires against the offer. Check the booking breakdown and applicable conditions before submitting a request.'],
      ],
      checklist: ['Objective and list of deliverables.', 'Source materials and final formats.', 'Timeline, revisions and working language.', 'What the price includes and excludes.'],
      question: 'Is Wisdom only for home services?', answer: 'No. Wisdom supports both in-person and online services. For digital or remote work, check that the selected offer uses an online format and covers your intended brief.',
    },
  },
  professionals: {
    ids: [1, 2, 56, 83, 84, 90, 174],
    es: {
      title: 'Ofrece servicios profesionales y trabaja como freelance en Wisdom', description: 'Publica tus servicios en Wisdom: describe tu especialidad, configura precios y disponibilidad y gestiona solicitudes de clientes desde el modo profesional.',
      intro: 'Wisdom permite buscar servicios y ofrecer tu propio trabajo desde una misma cuenta. El modo profesional está pensado para publicar ofertas y gestionar reservas, tanto presenciales como online. Una descripción precisa ayuda a que los clientes comprendan qué haces y qué están contratando.',
      sections: [
        ['Publica un servicio concreto', 'Explica la tarea que realizas, a quién va dirigida y qué resultado incluye. Es más útil describir una sesión, una intervención o un entregable que una lista genérica de capacidades. Aclara qué aporta el cliente y qué necesidades quedan fuera de la oferta.'],
        ['Configura modalidad, precio y disponibilidad', 'Indica si el trabajo es presencial u online y define sus condiciones. Revisa la forma de calcular el precio y los horarios antes de publicar. Mantén la información actualizada para que las solicitudes se ajusten al trabajo que realmente puedes asumir.'],
        ['Presenta tu experiencia con precisión', 'Completa el perfil con información que puedas respaldar. Cuando corresponda, muestra ejemplos de trabajo y explica tu especialización. La reputación debe reflejar servicios reales: evita promesas de resultados que no dependan solo de tu intervención.'],
        ['Gestiona solicitudes y condiciones', 'Revisa cada solicitud, su fecha y los detalles antes de aceptarla. Consulta las políticas de reservas, cancelaciones y pagos de Wisdom para conocer el flujo aplicable. Publicar una oferta no garantiza recibir clientes; la demanda depende de la búsqueda, la disponibilidad y la propuesta que ofreces.'],
      ],
      checklist: ['Tarea, alcance y entregables claros.', 'Modalidad y ubicación cuando corresponda.', 'Precios y disponibilidad actualizados.', 'Perfil y experiencia descritos de forma precisa.'],
      question: '¿Necesito otra cuenta para ofrecer y contratar servicios?', answer: 'Wisdom permite utilizar una misma cuenta para buscar servicios y acceder al modo profesional. Desde este último puedes publicar ofertas y gestionar las solicitudes que recibas.',
    },
    en: {
      title: 'Offer professional services and freelance with Wisdom', description: 'Publish services on Wisdom: describe your specialisation, set prices and availability and manage customer requests in professional mode.',
      intro: 'Wisdom lets you find services and offer your own work using the same account. Professional mode supports publishing offers and managing bookings for in-person and online work. A precise description helps customers understand what you do and what they are booking.',
      sections: [
        ['Publish a specific service', 'Describe the task, intended customer and included result. A defined session, visit or deliverable is more useful than a general list of abilities. Explain what the customer must provide and which requests fall outside the offer.'],
        ['Set format, price and availability', 'Specify whether the work is in person or online and define its conditions. Review pricing and scheduling before publishing. Keep information current so requests match work you can actually accept.'],
        ['Present your experience accurately', 'Complete your profile with information you can support. Where relevant, share examples and describe your specialisation. Reputation should reflect real services; avoid promising results that do not depend solely on your work.'],
        ['Manage requests and conditions', 'Review each request, its date and details before accepting. Consult Wisdom’s booking, cancellation and payment policies to understand the applicable process. Publishing an offer does not guarantee customers; demand depends on searches, availability and the service you offer.'],
      ],
      checklist: ['Clear task, scope and deliverables.', 'Format and location when relevant.', 'Current prices and availability.', 'Accurately described profile and experience.'],
      question: 'Do I need separate accounts to offer and book services?', answer: 'Wisdom lets you use one account to find services and access professional mode. Use professional mode to publish offers and manage incoming requests.',
    },
  },
  wellbeing: {
    ids: [31, 32, 34, 35, 36, 37, 54],
    es: {
      title: 'Bienestar y entrenamiento: cómo elegir un servicio', description: 'Explora entrenamiento personal, yoga, meditación, masajes y otras categorías de bienestar en Wisdom. Compara especialidad, modalidad y condiciones.',
      intro: 'Dentro de bienestar hay servicios con objetivos y requisitos muy distintos. Wisdom permite explorar entrenamiento personal, yoga, meditación, masajes y otras categorías presentes en el catálogo. Utiliza la descripción de cada oferta para entender su alcance antes de reservar.',
      sections: [
        ['Define el tipo de apoyo que buscas', 'Distingue entre una actividad dirigida, una sesión de entrenamiento o una atención de otra especialidad. Explica tu objetivo con claridad para comprobar si encaja con el servicio. Esta guía ayuda a elegir una oferta; no contiene recomendaciones de salud ni sustituye una valoración profesional.'],
        ['Revisa formación y especialización', 'Lee el perfil y comprueba la formación pertinente para el servicio que buscas. La presencia en una categoría no acredita por sí sola una titulación ni convierte todas las ofertas en equivalentes. Antes de reservar una atención especializada, confirma que quien la presta puede realizarla.'],
        ['Comprueba lugar, duración y material', 'Mira si la sesión se realiza a domicilio, en un lugar indicado o de forma online. Revisa su duración, el equipo necesario y lo que incluye el precio. En actividades físicas, confirma también el espacio y los materiales que requiere la sesión.'],
        ['Valora las condiciones de cada sesión', 'Consulta horarios y políticas de reserva y cancelación. Si buscas continuidad, revisa si hay posibilidad de recurrencia. Evita interpretar las descripciones o reseñas como una garantía de resultados; deben servir para conocer la oferta y la experiencia publicada.'],
      ],
      checklist: ['Tipo de sesión y objetivo.', 'Formación y especialización adecuadas.', 'Modalidad, ubicación y materiales.', 'Duración, precio y condiciones.'],
      question: '¿Todas las sesiones de bienestar son a domicilio?', answer: 'No. La modalidad depende de cada oferta. Revisa si es presencial u online y, si es presencial, dónde se realiza y si incluye desplazamiento.',
    },
    en: {
      title: 'Wellbeing and personal training: choosing a service', description: 'Explore personal training, yoga, meditation, massage and other wellbeing categories on Wisdom. Compare specialisation, format and conditions.',
      intro: 'Wellbeing services have different purposes and requirements. Wisdom lets you explore personal training, yoga, meditation, massage and other categories in the catalogue. Use each offer’s description to understand its scope before booking.',
      sections: [
        ['Define the support you are looking for', 'Distinguish between a guided activity, a training session and another specialist service. Explain your objective to check whether it matches the offer. This guide helps you choose a service; it does not provide health advice or replace a professional assessment.'],
        ['Review relevant training and specialisation', 'Read the profile and check qualifications relevant to the service. Being listed in a category does not itself establish a qualification or make all offers equivalent. Before booking specialist care, confirm that the provider is qualified to deliver it.'],
        ['Check location, duration and equipment', 'Look for whether the session is at home, at a specified location or online. Review its duration, required equipment and what the price includes. For physical activities, also check the space and materials needed for the session.'],
        ['Review individual session conditions', 'Check scheduling, booking and cancellation terms. If you want continuity, review whether recurring sessions are available. Do not interpret descriptions or reviews as a guarantee of results; use them to understand the offer and published experience.'],
      ],
      checklist: ['Session type and objective.', 'Relevant training and specialisation.', 'Format, location and equipment.', 'Duration, price and conditions.'],
      question: 'Are all wellbeing sessions delivered at home?', answer: 'No. Each offer defines its own format. Check whether it is in person or online and, for in-person sessions, the location and whether travel is included.',
    },
  },
  pets: {
    ids: [317, 318],
    es: {
      title: 'Cuidado de mascotas y paseadores de perros', description: 'Busca cuidado de mascotas y paseadores de perros en Wisdom. Compara tareas, horarios, experiencia y condiciones según las necesidades de tu animal.',
      intro: 'Para elegir cuidado de mascotas o paseos, la rutina del animal importa tanto como el horario. En Wisdom puedes explorar estas categorías y revisar las ofertas publicadas. Explicar las necesidades concretas ayuda a comprobar si un profesional y su servicio encajan con lo que buscas.',
      sections: [
        ['Describe la rutina y la tarea', 'Indica si necesitas un paseo o un servicio de cuidado y qué tareas esperas. Explica la especie, el tamaño y las rutinas relevantes, así como las pautas de manejo que el profesional deba conocer. Evita suponer que un paseo incluye otras tareas si la oferta no lo especifica.'],
        ['Comprueba duración y lugar', 'Revisa dónde empieza y termina el servicio, su duración y el horario. Si se realiza en tu domicilio, concreta el acceso; si implica recogida, aclara las condiciones. Las zonas de desplazamiento y la disponibilidad cambian según cada oferta.'],
        ['Compara experiencia y condiciones', 'Consulta el perfil y las reseñas publicadas, junto con la experiencia descrita con animales de necesidades similares. Aclara qué materiales aporta cada parte. La descripción del servicio debe permitir distinguir una visita puntual de otras modalidades de cuidado.'],
        ['Organiza la información práctica', 'Prepara instrucciones de contacto y las indicaciones acordadas para la rutina. Revisa la aceptación de la reserva antes del día previsto. Si necesitas sesiones repetidas, comprueba si la oferta admite recurrencia y qué horarios puedes solicitar.'],
      ],
      checklist: ['Tipo de tarea y rutina del animal.', 'Duración, ubicación y recogida si aplica.', 'Pautas de manejo y materiales.', 'Horario y confirmación de la reserva.'],
      question: '¿Un paseador también ofrece cuidado de mascotas?', answer: 'Depende del profesional y de la oferta publicada. Comprueba las tareas incluidas; no des por hecho que una reserva de paseo cubre alimentación, visitas u otros servicios.',
    },
    en: {
      title: 'Pet care and dog walkers', description: 'Find pet care and dog walkers on Wisdom. Compare tasks, schedules, experience and conditions around your animal’s needs.',
      intro: 'When choosing pet care or dog walking, your animal’s routine matters as much as the schedule. Explore these categories and review published offers on Wisdom. Describing specific needs helps you check whether a professional and their service suit your request.',
      sections: [
        ['Describe the routine and task', 'Specify whether you need a walk or a care service and which tasks you expect. Describe the animal, size, relevant routines and handling instructions. Do not assume a walk includes other tasks unless the offer says so.'],
        ['Check duration and location', 'Review where the service starts and finishes, its duration and timing. For home visits, clarify access; for collection, confirm the arrangements. Travel areas and availability vary by offer.'],
        ['Compare experience and conditions', 'Read the profile and published reviews alongside described experience with animals that have similar needs. Clarify who provides equipment. The description should help you distinguish a one-off visit from other care arrangements.'],
        ['Prepare practical information', 'Provide agreed contact and routine instructions. Check booking acceptance before the planned date. For repeated sessions, check whether recurring bookings are supported and which times you can request.'],
      ],
      checklist: ['Task and animal’s routine.', 'Duration, location and collection if relevant.', 'Handling instructions and equipment.', 'Schedule and booking confirmation.'],
      question: 'Does a dog walker also offer pet care?', answer: 'That depends on the professional and published offer. Check the included tasks rather than assuming a walking booking covers feeding, visits or other services.',
    },
  },
  events: {
    ids: [172, 173, 174, 175, 178, 181],
    es: {
      title: 'Profesionales para eventos: fotografía, catering y más', description: 'Explora fotografía, DJs, catering y organización de eventos en Wisdom. Define fecha, lugar, duración y entregables para comparar servicios.',
      intro: 'Los servicios para un evento dependen de una fecha, un espacio y un alcance concreto. Wisdom incluye categorías como organización de bodas, catering, fotografía, DJs, animación y seguridad. Cada profesional describe su trabajo y sus condiciones; prepara los datos del evento antes de comparar ofertas.',
      sections: [
        ['Comparte los datos básicos del evento', 'Indica fecha, ubicación, duración aproximada y tipo de celebración. El número de asistentes y las características del espacio pueden cambiar lo necesario para prestar el servicio. Distingue entre el tiempo de atención al evento y las tareas de preparación o montaje.'],
        ['Aclara equipo y entregables', 'En fotografía, consulta la cobertura y los archivos incluidos; en música o animación, revisa equipo, horarios y necesidades del espacio. Para catering, aclara el servicio descrito y la información que debes facilitar. No presupongas que alquileres, montaje o desplazamientos están incluidos.'],
        ['Coordina a los distintos profesionales', 'Si reservas varios servicios, define los accesos, puntos de contacto y horarios de cada uno. Comprueba que sus condiciones sean compatibles con las del lugar. Una reserva individual no implica la coordinación completa del evento salvo que la oferta lo especifique.'],
        ['Revisa fechas y cambios', 'Antes de enviar la solicitud, verifica todos los datos y las condiciones de cancelación. Comprueba la aceptación de cada profesional y conserva los detalles en la reserva. Si cambia el evento, revisa cómo debe gestionarse ese cambio en la app.'],
      ],
      checklist: ['Fecha, lugar, duración y asistentes.', 'Servicio, cobertura y entregables.', 'Equipo, montaje y desplazamientos.', 'Confirmación y condiciones ante cambios.'],
      question: '¿La reserva incluye toda la organización del evento?', answer: 'Solo si la oferta describe ese alcance. Un fotógrafo, un DJ o un servicio de catering pueden cubrir únicamente su parte; revisa las tareas de cada propuesta.',
    },
    en: {
      title: 'Event professionals: photography, catering and more', description: 'Explore photography, DJs, catering and event planning on Wisdom. Define the date, venue, duration and deliverables to compare offers.',
      intro: 'Event services depend on a specific date, venue and scope. Wisdom includes categories such as wedding planning, catering, photography, DJs, entertainment and security. Each professional describes their work and conditions; prepare your event details before comparing offers.',
      sections: [
        ['Share the event essentials', 'State the date, location, approximate duration and type of occasion. Guest numbers and venue features may affect service requirements. Distinguish between attendance at the event and preparation or setup work.'],
        ['Clarify equipment and deliverables', 'For photography, review coverage and included files; for music or entertainment, check equipment, timing and venue requirements. For catering, clarify the described service and information you must provide. Do not assume rentals, setup or travel are included.'],
        ['Coordinate different professionals', 'If booking several services, define access, contact points and schedules for each. Check that their conditions are compatible with the venue. An individual booking does not include full event coordination unless the offer specifies it.'],
        ['Review dates and changes', 'Check all details and cancellation conditions before requesting a booking. Confirm each professional’s acceptance and keep track of booking details. If the event changes, review how to manage that change in the app.'],
      ],
      checklist: ['Date, venue, duration and guest numbers.', 'Service scope, coverage and deliverables.', 'Equipment, setup and travel.', 'Confirmation and conditions for changes.'],
      question: 'Does a booking include organising the whole event?', answer: 'Only if the offer describes that scope. A photographer, DJ or caterer may cover only their own part; review the tasks included in each proposal.',
    },
  },
};
